spring:
  application:
    name: dating_site
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gg202106
    url: jdbc:mysql://106.53.106.106:3306/dating_site
    # 失效时间
  session:
    timeout: 86400
    store-type: redis
    # redis 配置
  redis:
    database: 10
    host: 106.53.106.106
    port: 6379
    password: Gg202106!!.
    timeout: 200000

server:
  port: 8080
  servlet:
    context-path: /api